target_sources(
  obs-studio
  PRIVATE
    docks/OBSDock.cpp
    docks/OBSDock.hpp
    docks/StreamInfoDock.cpp
    docks/StreamInfoDock.hpp
    docks/UnifiedChatDock.cpp
    docks/UnifiedChatDock.hpp
)
