target_sources(
  obs-studio
  PRIVATE
    utility/AdvancedOutput.cpp
    utility/AdvancedOutput.hpp
    utility/BaseLexer.hpp
    utility/BasicOutputHandler.cpp
    utility/BasicOutputHandler.hpp
    utility/CrashHandler.cpp
    utility/CrashHandler.hpp
    utility/FFmpegCodec.cpp
    utility/FFmpegCodec.hpp
    utility/FFmpegFormat.cpp
    utility/FFmpegFormat.hpp
    utility/FFmpegShared.hpp
    utility/GoLiveAPI_CensoredJson.cpp
    utility/GoLiveAPI_CensoredJson.hpp
    utility/GoLiveAPI_Network.cpp
    utility/GoLiveAPI_Network.hpp
    utility/GoLiveAPI_PostData.cpp
    utility/GoLiveAPI_PostData.hpp
    utility/MissingFilesModel.cpp
    utility/MissingFilesModel.hpp
    utility/MissingFilesPathItemDelegate.cpp
    utility/MissingFilesPathItemDelegate.hpp
    utility/MultitrackVideoError.cpp
    utility/MultitrackVideoError.hpp
    utility/MultitrackVideoOutput.cpp
    utility/MultitrackVideoOutput.hpp
    utility/ChannelAvatarCache.cpp
    utility/ChannelAvatarCache.hpp
    utility/MultiStreamManager.cpp
    utility/MultiStreamManager.hpp
    utility/MultistreamChannelStore.cpp
    utility/MultistreamChannelStore.hpp
    utility/MultistreamPreflight.cpp
    utility/MultistreamPreflight.hpp
    utility/MultistreamTaskPool.hpp
    utility/PlatformIconProvider.cpp
    utility/PlatformIconProvider.hpp
    utility/NativeEventFilter.hpp
    utility/OBSCanvas.cpp
    utility/OBSCanvas.hpp
    utility/OBSEventFilter.hpp
    utility/OBSProxyStyle.cpp
    utility/OBSProxyStyle.hpp
    utility/OBSTheme.hpp
    utility/OBSThemeVariable.hpp
    utility/OBSTranslator.cpp
    utility/OBSTranslator.hpp
    utility/PreviewProgramSizeObserver.cpp
    utility/PreviewProgramSizeObserver.hpp
    utility/QuickTransition.cpp
    utility/QuickTransition.hpp
    utility/RemoteTextThread.cpp
    utility/RemoteTextThread.hpp
    utility/RemuxEntryPathItemDelegate.cpp
    utility/RemuxEntryPathItemDelegate.hpp
    utility/RemuxQueueModel.cpp
    utility/RemuxQueueModel.hpp
    utility/RemuxWorker.cpp
    utility/RemuxWorker.hpp
    utility/ResizeSignaler.hpp
    utility/SceneRenameDelegate.cpp
    utility/SceneRenameDelegate.hpp
    utility/ScreenshotObj.cpp
    utility/ScreenshotObj.hpp
    utility/SettingsEventFilter.hpp
    utility/SimpleOutput.cpp
    utility/SimpleOutput.hpp
    utility/StartMultiTrackVideoStreamingGuard.hpp
    utility/StreamPlatform.cpp
    utility/StreamPlatform.hpp
    utility/StreamPlatformDisplay.hpp
    utility/SurfaceEventFilter.hpp
    utility/ThumbnailItem.cpp
    utility/ThumbnailItem.hpp
    utility/ThumbnailManager.cpp
    utility/ThumbnailManager.hpp
    utility/ThumbnailView.cpp
    utility/ThumbnailView.hpp
    utility/VCamConfig.hpp
    utility/audio-encoders.cpp
    utility/audio-encoders.hpp
    utility/display-helpers.hpp
    utility/item-widget-helpers.cpp
    utility/item-widget-helpers.hpp
    utility/models/multitrack-video.hpp
    utility/obf.c
    utility/obf.h
    utility/platform.hpp
    utility/system-info.hpp
    utility/undo_stack.cpp
    utility/undo_stack.hpp
)

# The Windows credential-store backend is added by os-windows.cmake. Every other
# platform still needs a definition, otherwise OAuthTokenSet fails to link.
if(NOT OS_WINDOWS)
  target_sources(obs-studio PRIVATE utility/SecureTokenStore.hpp utility/SecureTokenStore_Stub.cpp)
endif()
